baseurl: /utrecht
permalink: pretty
markdown: kramdown
paginate: 5
repo: utrecht
github_org: maptime
maptime:
  chapter: MaptimeUtrecht
  twitter: MaptimeUtrecht
  #disqus: YOUR DISQUS USERNAME

future: true
gems:
  - jekyll-feed
